apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wis2bridge.fullname" . }}
  labels:
    {{- include "wis2bridge.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "wis2bridge.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wis2bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wis2bridge.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.global.WIS2IMAGETAG }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.global.KAFKA_BROKER }}
            - name: TOPICS
              value: {{ .Values.global.TOPICS }}
            - name: WIS_BROKER_HOST
              value: {{ .Values.global.WIS_BROKER_HOST }}
            - name: WIS_BROKER_PORT
              value: {{ quote .Values.global.WIS_BROKER_PORT }}
            - name: VALIDATE_SSL
              value: {{ .Values.global.VALIDATE_SSL | quote  }}
            - name: WIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wis-secrets
                  key: wis-username
            - name: WIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wis-secrets
                  key: wis-password
            - name: LOG_LEVEL
              value: {{ .Values.global.LOG_LEVEL }}
            - name: KAFKA_TOPIC
              value: {{ .Values.global.KAFKA_TOPIC }}
            - name: REPORTING_THRESHOLD
              value: {{ quote .Values.global.REPORTING_THRESHOLD }}
            - name: BATCH_SIZE
              value: {{ quote .Values.global.BATCH_SIZE }}
            - name: CLIENT_ID
              value: {{ .Values.global.CLIENT_ID }}
            - name: CUSTOMERS_HOST
              value: {{ .Values.global.CUSTOMERS_HOST }}
            - name: CUSTOMERS_PORT
              value: {{ quote .Values.global.CUSTOMERS_PORT }}
            - name: METRIC_PORT
              value: {{ quote .Values.global.METRIC_PORT }}
            - name: ROUTING_FILE
              value : {{ .Values.routing_file }}
          ports:
            - name: metrics
              containerPort: {{ .Values.global.METRIC_PORT }} 
              protocol: TCP
          volumeMounts:
            - name: routing-config-volume
              mountPath: /app/message-routing.json
              subPath: message-routing.json
      volumes:
        - name: routing-config-volume
          configMap:
            name: {{ include "wis2bridge.fullname" . }}-routing-config
