apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 20Gi  # Match the request in your PVC
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2  # Must match the storage class expected by PVC
  awsElasticBlockStore:
    volumeID: "ol-06963cb8a07459fee"
    fsType: "ext4"
