apiVersion: v1
kind: Secret
metadata:
  name: wis-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ printf "%s" .Values.postgresql.auth.password | b64enc | quote }}
  s3-access-key: {{ printf "%s" .Values.s3.S3_ACCESS_KEY | b64enc | quote }}
  s3-endpoint: {{ printf "%s" .Values.s3.S3_ENDPOINT | b64enc | quote }}
  s3-secret-key: {{ printf "%s" .Values.s3.S3_SECRET_KEY | b64enc | quote }}
  s3-hive-metastore-user: {{ printf "%s" .Values.hive.HIVE_METASTORE_USER | b64enc | quote }}
  s3-hive-metastore-password: {{ printf "%s" .Values.hive.HIVE_METASTORE_PASSWORD | b64enc | quote }}
  s3-hive-metastore-jdbc-url: {{ printf "%s" .Values.hive.HIVE_METASTORE_JDBC_URL | b64enc | quote }}
  s3-hive-metastore-wareshouse-dir: {{ printf "%s" .Values.hive.HIVE_METASTORE_WAREHOUSE_DIR | b64enc | quote }}
  s3-hive-metastore-users-admin-role: {{ printf "%s" .Values.hive.HIVE_METASTORE_USERS_IN_ADMIN_ROLE | b64enc | quote }}
  wis-username: {{ printf "%s" .Values.wis.WIS_USERNAME | b64enc | quote }}
  wis-password: {{ printf "%s" .Values.wis.WIS_PASSWORD | b64enc | quote }}
  offsets-user: {{ printf "%s" .Values.postgresql.auth.OFFSETS_USER | b64enc | quote }}
  offsets-password: {{ printf "%s" .Values.postgresql.auth.OFFSETS_PASSWORD | b64enc | quote }} 