image:
  repository: tproescholdt/wis2obsproc-output-processor
  pullPolicy: IfNotPresent

data_mapping_file: /app/data-mapping-observations.txt
keys: wigos_id,notification_data_id,result_time
group_id: "my-consumer-output-1"

replicaCount: 1

serviceAccount:
  create: true

autoscaling:
  enabled: false
