{
 "title": "Kafka Topics Metrics",
 "description": "With Kafka Topics Metrics Dashboard we can visualize the Metrics related to the topic. We can select the particular topic from the dropdown and see the data related to this topic.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "env",
    "label": "ENV",
    "query": "label_values(system_uptime, env)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(kafka_controller_activecontrollers__1, instance)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(system_uptime, service)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_MessagesInPerSec_Count, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Message in by Topic",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesinpersec_count",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in by Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate{}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in by 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in by 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate[15m])\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out by Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesoutpersec_oneminuterate",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out by 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kafka_server_brokertopicmetrics_bytesoutpersec_oneminuterate[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out by 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kafka_server_brokertopicmetrics_bytesoutpersec_oneminuterate[15m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes in Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesinpersec_oneminuterate{}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "TotalProduceRequest Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_totalproducerequestspersec_oneminuterate{}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "TotalFetchRequest Per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalfetchrequestspersec_oneminuterate{}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}